version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      target: dev
    image: frontend
    ports:
      - "18080:18080"
    environment:
      - DEV_HOST=0.0.0.0
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/sner/frontend
    depends_on:
      - server

  server:
    build:
      context: ./server
      target: dev
    ports:
      - "18000:18000"
    volumes:
      - type: bind
        source: ./server
        target: /opt/sner/server
    depends_on:
      - postgres

  planner:
    build:
      context: ./server
      target: dev_planner
    depends_on:
      - server

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sner

volumes:
  db-data:
