version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      target: prod
    image: frontend
    ports:
      - "18080:18080"
    environment:
      - PREVIEW_HOST=0.0.0.0
    depends_on:
      - server

  server:
    build:
      context: ./server
      target: prod
    ports:
      - "18000:18000"
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  db-data:
