version: "3.7"

services:

  server:
    build:
      context: ..
      dockerfile: docker/server/Dockerfile
    container_name: sner_server
    environment:
      SNER_SERVER_SECRET_KEY:
      SNER_SERVER_DB_PASSWORD:
      SNER_AGENT_APIKEY:

      SNER_CONFIG: |
        server:
          secret_key: "${SNER_SERVER_SECRET_KEY}"
          sqlalchemy_database_uri: "postgresql://sner:${SNER_SERVER_DB_PASSWORD}@db/sner"
    volumes:
      - vardata:/var/lib/sner
    ports:
      - 18000:18000
    restart: always
    depends_on:
      - db
    networks:
      - backend

  agent:
    build:
      context: ..
      dockerfile: docker/agent/Dockerfile
    container_name: sner_agent
    environment:
      SNER_AGENT_APIKEY:

      SNER_CONFIG: |
        agent:
          server: "http://server:18000"
          apikey: "${SNER_AGENT_APIKEY}"
    restart: always
    depends_on:
      - server
    networks:
      - backend

  db:
    image: postgres:15-bookworm
    container_name: sner_db
    volumes:
      - dbdata:/var/lib/postgresql
    environment:
      SNER_SERVER_DB_PASSWORD:

      POSTGRES_DB: sner
      POSTGRES_USER: sner
      POSTGRES_PASSWORD: "${SNER_SERVER_DB_PASSWORD}"
    restart: always
    networks:
      - backend

volumes:
  dbdata:
  vardata:

networks:
  backend:
