name: Frontend nodejs CI

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-nodejs.yml"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-nodejs.yml"

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "frontend"
      - run: npm install
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run test
