name: Frontend CI

on:
  workflow_call:

defaults:
  run:
    working-directory: frontend

jobs:
  code_quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "frontend"
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run lint
