name: Selenium tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "frontend"

      - name: Build frontend assets
        run: |
          npm install
          npm run build
        working-directory: frontend

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          sudo apt-get update
          sudo make install
          sudo make install-dev
        working-directory: server
      - run: |
          sudo apt-get -y install postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE sner_test"
          sudo -u postgres psql -c "CREATE USER ${USER}"
          mkdir -p /tmp/sner_test_var
        working-directory: server

      - name: Run selenium tests with pre-built assets
        run: . venv/bin/activate && PYTEST_FRONTEND=nobuild make test-selenium
        working-directory: server
