name: Semgrep OSS scan

on:
  workflow_call:

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-22.04

    container:
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4

      # does not repor error on findings for now
      - run: semgrep scan --config auto
