name: Server python CI

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/server-python.yml"
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/server-python.yml"

defaults:
  run:
    working-directory: server

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: sudo apt-get update
      - run: sudo make install
      - run: |
          sudo apt-get -y install postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE sner_test"
          sudo -u postgres psql -c "CREATE USER ${USER}"
          mkdir -p /tmp/sner_test_var
      - run: . venv/bin/activate && make coverage
      - run: . venv/bin/activate && make lint
